### ISSUE TITLE
npm RunKit example broken?

### ISSUE THREAD

**Issue by iehdk** [mljs/levenberg-marquardt#10]
https://npm.runkit.com/ml-levenberg-marquardt

This seems to spew errors:

<img width="453" alt="screen shot 2018-02-02 at 16 45 10" src="https://user-images.githubusercontent.com/29797781/35741582-82da3980-0838-11e8-895f-d8f318e4be93.png">

**Comment by maasencioh** [comment]
@iehdk now the runkit example works fine, thanks for pointing it out

**Comment by iehdk** [comment]
no problem :o)
