### ISSUE TITLE
Including ml-levenberg-marquardt via CDN

### ISSUE THREAD

**Issue by GregStanton** [mljs/levenberg-marquardt#38]
Hi!

Thanks for making this library. In order to use it, it looks like I need to install it via npm. Do you have any tips on how I might install it via CDN instead? 

I tried including the main file and its dependencies in my index.html file through script tags, using the code below.

```html
<script src = "https://unpkg.com/ml-levenberg-marquardt/lib/index.js"> </script>
<script src = "https://unpkg.com/is-any-array@0.1.1/lib/index.js"></script>
<script src = "https://unpkg.com/ml-matrix@6.7.0/matrix.umd.js"></script>
<script src = "https://unpkg.com/ml-array-rescale@1.3.4/lib/index.js"></script>
<script src = "https://unpkg.com/ml-array-min@1.2.1/lib/index.js"></script>
<script src = "https://unpkg.com/ml-array-max@1.2.2/lib/index.js"></script>
```
Unfortunately, this does not appear to have worked. In case it helps, you can see the [rest of my code](https://editor.p5js.org/highermathnotes/sketches/1fQt_eVpL) in the p5.js web editor. 

If it were possible to include the library from a single URL in one script element, that would be especially nice. In particular, it would make the library more accessible to beginner programmers. I appreciate any help you can provide.

Thank you,
Greg

**Comment by jacobq** [comment]
> Do you have any tips on how I might install it via CDN instead?

You could try https://www.jsdelivr.com/
e.g. https://cdn.jsdelivr.net/npm/ml-levenberg-marquardt@3.1.0

**Comment by GregStanton** [comment]
Thanks for your response! Yeah, I realized after I posted this issue that `require()` would cause problems, but it helps to know that I homed in on the right issue. It looks like webpack or something similar would provide a good solution. 

For my purposes, I figured I'd try to see if I could quickly bundle the scripts manually without installing webpack. It took a little work, but I actually managed to do it; at least, the bundled library produced sensible output on my simple test case. I basically just pasted all the files into a single file in an appropriate order, deleted the calls to `require()`, deleted the lines setting `module.exports`, replaced `isArray` with `Array.isArray`, deleted redundant definitions, and made some other small changes.

In case this is useful to anyone else, the bundled file is available as part of a [p5.js sketch that I made for testing](https://editor.p5js.org/highermathnotes/sketches/1fQt_eVpL). If I make changes later and you don't see the file right away, just click at the top left of the editor to expand the file manager. The library code and its dependencies are all in the file ml-levenberg-marquardt.js, under Sketch Files.

Should we keep the issue open? My immediate issue appears to be solved, but perhaps it would be nice to provide a cleaner solution for others who want to use the library in the browser. I suppose that if I didn't make any mistakes, you could use the file I made, but I wouldn't count on all of my changes for general use. It's possible I broke something.

**Comment by jacobq** [comment]
> Should we keep the issue open?

If you feel that your issue is resolve then my opinion is that the issue should be closed. (I like to think of "open issues" as questions in need of answers and bugs in need of fixes. Feature requests can be OK, but if there aren't plans / schedules for implementing them then the danger is that the issues can become noise to sift through.)

**Comment by GregStanton** [comment]
Sure, no problem! I'll close the issue. Thanks again.

In case it helps anyone else, I'll attach two files here. The first file (levenberg-marquardt.txt) worked in the browser on a simple test case that used vanilla JavaScript. The second file (p5-levenberg-marquardt.js) worked on a more complicated test case as part of a p5 sketch; I had to make additional changes to the Levenberg-Marquardt code to make this work, due to a naming conflict between the min() and max() functions in levenberg-marquardt.js and the p5.js functions of the same name. Both are JavaScript files, but I'm attaching them as plain text files, since attaching a .js file to a comment isn't supported on GitHub.

[levenberg-marquardt.txt](https://github.com/mljs/levenberg-marquardt/files/6187261/levenberg-marquardt.txt)
[p5-levenberg-marquardt.txt](https://github.com/mljs/levenberg-marquardt/files/6187336/p5-levenberg-marquardt.txt)
