### ISSUE TITLE
Add simple linear regression example

### ISSUE THREAD

**Issue by opatiny** [mljs/levenberg-marquardt#51]
I have been trying to use the library and am struggling a bit with the results I'm obtaining. I think it would be really practical to have a very basic linear regression example to help understand how the library works.

I have also checked the testcases and haven't seen a very basic test easy to understand.

**Comment by opatiny** [comment]
Hi @jobo322 , thanks for your answer! I managed to get it work but I still think an example could be useful ;)

**Comment by jacobq** [comment]
@opatiny Now that you've figured it out, would you be willing to submit a PR that improves the documentation/examples? I can help edit & review it.
