### ISSUE TITLE
What does sampleFunction's sigmoidFunction parameters mean?

### ISSUE THREAD

**Issue by iehdk** [mljs/levenberg-marquardt#9]
In https://github.com/mljs/levenberg-marquardt/blob/master/test/test.js

please explain the parameters:

`let sampleFunction = sigmoidFunction([2, 2, 2]);`

**Comment by maasencioh** [comment]
This is the original function:

```javascript
function sigmoidFunction([a, b, c]) {
    return (t) => (a / (b + Math.exp(-t * c)));
}
```

The parameters are passed to the function to the one that you want to fit. So that is the equivalent of having:

```javascript
let sampleFunction = (t) => (2/ (2 + Math.exp(-t * 2)));
```

**Comment by iehdk** [comment]
Hm, I don't get it. I don't get the correct output. Line 56 of `curve_fit.util.js` should be fed what? 

https://gist.github.com/iehdk/57f48322487a16a1d7500ae95a252c7f

**Comment by maasencioh** [comment]
@iehdk you have to take in mind that depending on the data it's possible that the method doesn't converge. Did you make it work out as expected?

**Comment by iehdk** [comment]
No, I am afraid I am stuck. My test data set should be able to create a nice fit. It does so in XLFit (which is a commercial piece of software). I'd much rather use some open source tool.

**Comment by iehdk** [comment]
That would be super! Lets close this thread then. Let me know if I can test anything or help out in any way!
